platform :ios, '6.0'
pod 'GCDiscreetNotificationView', '1.0.0'
pod 'ECSlidingViewController', '0.9.0'
pod 'FontAwesomeIconFactory', '1.0.1'
pod 'BRBluetoothManager', '0.0.1'
pod 'TestFlightSDK', '1.2.3.beta1'
